[package]
name = "gst-streaming"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
gst.workspace = true
gst-video.workspace = true
gst-pbutils.workspace = true
common.workspace = true
motion.workspace = true
detection.workspace = true
storage.workspace = true
parking_lot.workspace = true
cairo-rs.workspace = true