[package]
name = "gst-streaming"
version = "0.1.0"
edition = "2021"

[dependencies]
inference = { path = "../inference" }
gst = { package = "gstreamer", version = "0.23.5" }
gst-app = { package = "gstreamer-app", version = "0.23.5" }
gst-video = { package = "gstreamer-video", version = "0.23.5" }
gst-pbutils = { package = "gstreamer-pbutils", version = "0.23.5" }
cairo-rs = { version = "0.20.7" }
anyhow = "1.0"