[package]
name = "detection"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
parking_lot.workspace = true
gst-video.workspace = true
opencv.workspace = true
rayon.workspace = true
ndarray.workspace = true

ort = { version = "2.0.0-rc.9", features = ["ndarray", "cuda"] }

[features]
load-dynamic = ["ort/load-dynamic"]
cuda = ["ort/cuda"]