[package]
name = "streaming"
version = "0.1.0"
edition = "2024"

[dependencies]
gst = { package = "gstreamer", version = "0.23.5" }
gst-app = { package = "gstreamer-app", version = "0.23.5" }
gst-video = { package = "gstreamer-video", version = "0.23.5" }
gst-pbutils = { package = "gstreamer-pbutils", version = "0.23.5" }
cairo-rs = { version = "0.20.7" }
anyhow = "1.0"
opencv = "0.94.4"
detection = { path = "../detection" }
bytes = "1.10.1"
image="0.25.6"
ndarray = "0.16.1"