[api]
host = "127.0.0.1"
port = 9876
upload_dir = "uploads"

[database]
url = "localhost"
port = 5432
user = "myuser"
password = "mypassword"
database = "myapp"
migrations_path = "migrations"

[mq]
url = "localhost"
port = 5672
user = "guest"
password = "guest"

[object_detection_model]
path = "models/yolo11s.onnx"
input_width = 640
input_height = 640

[face_detection_model]
path = "models/yolov11s-face.onnx"
input_width = 640
input_height = 640

[face_recognition_model]
path = "models/face-recognition.onnx"
input_width = 160
input_height = 160

[worker]
worker_count = 1