[api]
host = "127.0.0.1"
port = 9876
upload_dir = "uploads"

[database]
url = "localhost"
port = 5432
user = "myuser"
password = "mypassword"
database = "myapp"
migrations_path = "migrations"

[mq]
url = "localhost"
port = 5672
user = "guest"
password = "guest"

[object_detection_model]
path = "models/yolo11s.onnx"
input_width = 640
input_height = 640

[face_detection_model]
path = "models/yolo11s-pose_widerface.onnx"
input_width = 800
input_height = 800

[face_recognition_model]
path = "models/face-recognition.onnx"
input_width = 160
input_height = 160


[face_database]
path = "assets/face_database"
db_file = "assets/face_database.json"
similarity_threshold = 0.7

[worker]
worker_count = 1


