[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
uuid.workspace = true
actix-web.workspace = true
actix-multipart.workspace = true
serde.workspace = true
sqlx.workspace = true
tokio.workspace = true
regex.workspace = true


# refacor
thiserror = "2.0.12"
futures = "0.3.31"
chrono = { version = "0.4.40", features = ["serde"] }
sanitize-filename = "0.6.0"
lapin = "2.5.1"
storage = { path = "../storage" }
queue = { path = "../queue" }
common = { path = "../common" }