[database]
url = "localhost"
port = 5432
user = "myuser"
password = "mypassword"
database = "myapp"
migrations_path = "migrations"

[mq]
url = "localhost"
port = 5672
user = "guest"
password = "guest"
